[project]
name = "harness"
version = "1.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "luaparser>=3.3.0",
    "PyYAML>=6.0.0",
]

[dependency-groups]
quality = [
    "lizard==1.23.0",
]

[tool.uv]
required-version = "==0.10.12"

[project.optional-dependencies]
docs = [
    "sphinx",
    "sphinx-lua",
    "sphinxcontrib-luadomain",
]
