name: CI

on:
  push:
    branches:
      - main
      - dev/**
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  ci:
    name: Lint, Test and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        

      - name: Set up Task
        uses: arduino/setup-task@v1

      - name: Set up Lua 5.1
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1"

      - name: Lint Lua with Selene
        uses: YoloWingPixie/selene-lua-linter-action@v1
        with:
          config-path: 'selene.toml'
          lint-path: 'src/'
          report-as-annotations: 'true'
          working-directory: '.'

      - name: Run format, tests, and build
        run: |
          chmod +x stylua/stylua || true
          task format:check
          task test
          task build:cd

      - name: Upload build artifact
        if: ${{ success() && hashFiles('dist/harness.lua') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: harness.lua
          path: dist/harness.lua

