name: CI

on:
  push:
    branches:
      - main
      - dev/**
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  ci:
    name: Lint, Test and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        

      - name: Set up Task
        uses: arduino/setup-task@v1

      - name: Install Lua 5.1
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.1
          sudo ln -sf /usr/bin/lua5.1 /usr/local/bin/lua

      - name: Lint Lua with Selene
        uses: YoloWingPixie/selene-lua-linter-action@v1
        with:
          config-path: 'selene.toml'

      - name: Run format, tests, and build
        run: |
          task format:check
          task test
          task build:cd

      - name: Upload build artifact
        if: ${{ success() && hashFiles('dist/harness.lua') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: harness.lua
          path: dist/harness.lua

