name: CI

on:
  push:
    branches:
      - main
      - dev/**
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  ci:
    name: Lint, Test and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        

      - name: Set up Task
        uses: arduino/setup-task@v1

      - name: Install Lua and LuaRocks
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.4 luarocks

      - name: Install Lua tooling (luacheck, luacov)
        run: |
          sudo luarocks install luacheck
          sudo luarocks install luacov

      - name: Run CI task
        run: |
          task ci

      - name: Upload build artifact
        if: ${{ success() && hashFiles('dist/harness.lua') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: harness.lua
          path: dist/harness.lua

