name: Prerelease (PR builds)

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write

jobs:
  prerelease:
    name: Build and tag prerelease
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up Task
        uses: arduino/setup-task@v1

      - name: Install Lua and LuaRocks
        shell: powershell
        run: |
          choco install -y lua
          choco install -y luarocks

      - name: Install Lua tooling (luacheck)
        shell: powershell
        run: |
          refreshenv
          luarocks install luacheck

      - name: Build (CD)
        shell: powershell
        run: |
          task build:cd

      - name: Create prerelease tag
        if: success()
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          # Read version stamped into dist/harness.lua header (fallback to date)
          VERSION=$(grep -Eo 'HARNESS_VERSION\s*=\s*"[^"]+"' dist/harness.lua | sed -E 's/.*"(.*)"/\1/')
          if [ -z "$VERSION" ]; then VERSION=$(date +%Y.%m.%d); fi
          SHA=${GITHUB_SHA::7}
          TAG="v$VERSION-prerelease.$(echo $GITHUB_HEAD_REF | tr '/' '-')+$SHA"
          echo "Creating prerelease tag $TAG"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag -f "$TAG" "$GITHUB_SHA"
          git push -f origin "$TAG"

      - name: Upload prerelease artifact
        uses: actions/upload-artifact@v4
        with:
          name: harness-prerelease
          path: dist/harness.lua

